Feature/filename conventions
YAWNICK/TEQST_Backend pull request #9
Opened 2021-04-30 15:35 UTC by Doomse

This feature turned out to reach quite a bit further than originally intended. The following things are changed by this feature branch:

- All files managed by the program are now registered as file-fields and their naming conventions are altered
- The creation of audio, stm and log files is now split into small object methods instead of one big static method
- The creation of stm headers is moved to a static helper method and is completely in code (no template copy/paste file)

The current (cleaner) implementation has the side effect of creating empty placeholder files quite early.
    Maybe this behaviour has to be changed? (I will get this checked)

Maybe squash these commits before merging, since they have many back-and-forth changes (but not a must)?

2021-05-02 10:34 UTC, YAWNICK requested changes
Looks good, except we may run into problems with your change to the TextRecording.is_finished() method. (see comment)

2021-05-02 10:34 UTC, YAWNICK commented on TEQST/recordingmgmt/models.py
> +        return self.srecs.count() >= self.text.sentence_count()
You need to be careful with the change from == to >=. This method is also used in the Text.has_any_finished_recordings() method and the SentenceRecordingSerializer. Maybe make a new method? Or adjust the if statement where yu use your changed method.

2021-05-02 10:39 UTC, YAWNICK commented
Concerning:
- early empty placeholder files: I think that's fine.
- squash merge: In this case I'm also in favor of a squash merge.

2021-05-03 18:12 UTC, Doomse commented on TEQST/recordingmgmt/models.py
> +        return self.srecs.count() >= self.text.sentence_count()
This was supposed to be a mostly cosmetic change, since the > case of the >= should never actually happen, since having more sentence recordings than sentences would mean some kind of duplicate- or phantom-recording would exist. This change would ensure that such a corrupted dataset would still be considered finished, but we can pull that change back without issue if you don't like it. 
Since we are dealing with ints not floats, the exact comparison would work fine aswell, its just generally good practice (afaik) to check whether or not a value has reached or surpassed a threshhold/limit instead of checking for exact hits (this scenario doesn't fully translate, but it's close enough imo)

2021-05-05 13:24 UTC, YAWNICK commented on TEQST/recordingmgmt/models.py
> +        return self.srecs.count() >= self.text.sentence_count()
After reading your comment I looked at it again and realized that - yes - it doesn't actually change anything as long as everything works as expected. I somehow thought It would make a tetrecording finish earlier, but it doesn't. As has as handling corrupt datasets is concerned I don't have a preference, so we can just make the change.

2021-05-05 13:24 UTC, YAWNICK approved these changes

2021-05-12 14:26 UTC, merged